[project]
name = "smib"
version = "1.4.0"
description = "SoMakeIt BOT"
readme = "README.md"
requires-python = ">=3.12.3,<4.0.0"
authors = [
    { name = "Sam Cork", email = "sam57719@gmail.com" }
]
dependencies = [
    "python-decouple>=3.8,<4.0.0",
    "slack-bolt>=1.18.1,<2.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "flask>=3.0.2,<4.0.0",
    "simple-websocket-server>=0.4.4,<1.0.0",
    "websocket-client>=1.7.0,<2.0.0",
    "websockets>=12.0,<13.0",
    "tornado>=6.4,<7.0",
    "injectable>=3.4.7,<4.0.0",
    "apscheduler>=3.10.4,<4.0.0",
    "uvicorn>=0.30.1,<1.0.0",
    "dataclasses-json>=0.6.4,<1.0.0",
    "aiohttp>=3.9.5,<4.0.0",
    "pymongo>=4.7.0,<5.0.0",
    "mogo>=0.6.0,<1.0.0",
    "fastapi>=0.115.6,<1.0.0"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
